version: '3'

services:
  web-app:
    container_name: plov
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./marketplace:/marketplace
    environment:
      - DB_HOST=database
      - DB_NAME=database
      - DB_USER=user
      - DB_PASS=pass
    
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
  
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass