# Generated by Django 5.0 on 2023-12-27 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Заказ находится на рассмотрении', 'Free'), ('Заказ находится в работе', 'Accepted'), ('Заказ доставлен в постамат', 'Delivered'), ('Клиент забрал заказ', 'Competed'), ('Заказ был отменён', 'Cancel')], default='Заказ находится на рассмотрении', max_length=150, verbose_name='Статус заказа')),
                ('courier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='courier.courier', verbose_name='Курьер')),
                ('parcel_locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='courier.parcellocker', verbose_name='Постамат')),
                ('products', models.ManyToManyField(to='market.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
