# Generated by Django 5.0 on 2024-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_order_products_order_order_price_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Электроника и бытовая техника', 'Electronics'), ('Одежда и аксессуары', 'Cloth'), ('Товары для дома и интерьера', 'Interior')], max_length=150, verbose_name='Категория товара'),
        ),
    ]
