# Generated by Django 5.0 on 2023-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcellocker',
            name='status',
            field=models.CharField(choices=[('Свободен', 'Free'), ('Занят', 'Busy')], default=1, max_length=150, verbose_name='Статус постамата'),
            preserve_default=False,
        ),
    ]
